@startuml
actor Client
participant "Orthense Identity Server" as AuthServer
participant "Orthense FHIR API" as Api

== Obtention du Token ==
Client -> AuthServer: POST /connect/token (client_id, client_secret, grant_type=client_credentials)
AuthServer -> Client: { "access_token": "eyJhbGciOiJI...", "expires_in": 3600 }

== Appel au service avec le Token ==
Client -> Api: GET /resource (Authorization: Bearer access_token)
Api -> Client: Réponse API

== Renouvellement du Token ==
... Lorsque expires_in est atteint ...
Client -> AuthServer: POST /connect/token (client_id, client_secret, grant_type=client_credentials)
AuthServer -> Client: { "access_token": "nouveau_token", "expires_in": 3600 }
@enduml
